"use strict";

angular.module("app")
	.constant("Config", {
		"host": "/v1",
		"socket_host": "/",
		"ruleType": [
			{
				"id": 1,
				"name": "Asset"
			},
			{
				"id": 2,
				"name": "Zone"
			}
			// ,
			// {
			// 	"id":3,
			// 	"name":"Asset Type"
			// },
			// {
			// 	"id":4,
			// 	"name":"Zone Type"
			// }
		],
		"softwaretype":[
			{
				"id":1,
				"name": "Node"
			},
			{
				"id":2,
				"name":"Gateway Node"
			},
			{
				"id":3,
				"name": "Gateway"
			}
		],
        "Devices": [{
            "id": 1,
            "name": "Beacon"
        },
        {
            "id": 2,
            "name": "Receiver"
        },
        {
            "id": 3,
            "name": "Zone Gateway"
        },
        {
            "id": 4,
            "name": "Test Beacon"
        },
        {
            "id": 5,
            "name": "RFID Card"
        },
        {
            "id": 6,
            "name": "Bus Gateway"
        },
        {
            "id": 7,
            "name": "Food Cart Gateway"
        },
        {
            "id": 8,
            "name": "Control Room Gateway"
        },
        {
            "id": 9,
            "name": "Provisioning Device Gateway"
        }
	],
	"Leds":[{
		"name":"LED One",
		"value": 1
	},
	{
		"name":"LED Two",
		"value": 2
	},
	{
		"name": "LED Three",
		"value": 3
	},
	{
		"name":"LED Four", 
		"value": 4
	},
	{
		"name":"LED Five",
		"value": 5
	},
	{
		"name":"LED Six",
		"value": 6
	},
	{
		"name":"LED Seven",
		"value": 7
	
	},
	{
		"name":"LED Eight",
		"value": 8
	},
	{
		"name":"LED Nine",
		"value": 9
	},
 	{
		"name":"LED Ten",
		"value": 10
	},
  	{
		"name":"LED Eleven", 
		"value": 11
	},
   	{
		"name":"LED Twelve", 
		"value": 12
	}
	],

		"font_awsom_icon": [
			{ "c": "fas fa-adjust", "l": "Adjust" },
			{ "c": "fab fa-adn", "l": "Adn" },
			{ "c": "fas fa-align-center", "l": "Align center" },
			{ "c": "fas fa-align-justify", "l": "Align justify" },
			{ "c": "fas fa-align-left", "l": "Align left" },
			{ "c": "fas fa-align-right", "l": "Align right" },
			{ "c": "fab fa-amazon", "l": "Amazon" },
			{ "c": "fas fa-ambulance", "l": "Ambulance" },
			{ "c": "fas fa-anchor", "l": "Anchor" },
			{ "c": "fab fa-android", "l": "Android" },
			{ "c": "fab fa-angellist", "l": "Angellist" },
			{ "c": "fas fa-angle-double-down", "l": "Angle double down" },
			{ "c": "fas fa-angle-double-left", "l": "Angle double left" },
			{ "c": "fas fa-angle-double-right", "l": "Angle double right" },
			{ "c": "fas fa-angle-double-up", "l": "Angle double up" },
			{ "c": "fas fa-angle-down", "l": "Angle down" },
			{ "c": "fas fa-angle-left", "l": "Angle left" },
			{ "c": "fas fa-angle-right", "l": "Angle right" },
			{ "c": "fas fa-angle-up", "l": "Angle up" },
			{ "c": "fab fa-apple", "l": "Apple" },
			{ "c": "fas fa-archive", "l": "Archive" },
			{ "c": "fas fa-arrow-circle-down", "l": "Arrow circle down" },
			{ "c": "fas fa-arrow-circle-left", "l": "Arrow circle left" },
			{ "c": "fas fa-arrow-circle-right", "l": "Arrow circle right" },
			{ "c": "fas fa-arrow-circle-up", "l": "Arrow circle up" },
			{ "c": "fas fa-arrow-down", "l": "Arrow down" },
			{ "c": "fas fa-arrow-left", "l": "Arrow left" },
			{ "c": "fas fa-arrow-right", "l": "Arrow right" },
			{ "c": "fas fa-arrow-up", "l": "Arrow up" },
			{ "c": "fas fa-arrows-alt", "l": "Arrows alt" },
			{ "c": "fas fa-asterisk", "l": "Asterisk" },
			{ "c": "fas fa-at", "l": "At" },
			{ "c": "fas fa-backward", "l": "Backward" },
			{ "c": "fas fa-balance-scale", "l": "Balance scale" },
			{ "c": "fas fa-ban", "l": "Ban" },
			{ "c": "fas fa-barcode", "l": "Barcode" },
			{ "c": "fas fa-bars", "l": "Bars" },
			{ "c": "fas fa-battery-empty", "l": "Battery empty" },
			{ "c": "fas fa-battery-full", "l": "Battery full" },
			{ "c": "fas fa-battery-half", "l": "Battery half" },
			{ "c": "fas fa-battery-quarter", "l": "Battery quarter" },
			{ "c": "fas fa-battery-three-quarters", "l": "Battery three quarters" },
			{ "c": "fas fa-bed", "l": "Bed" },
			{ "c": "fas fa-beer", "l": "Beer" },
			{ "c": "fab fa-behance", "l": "Behance" },
			{ "c": "fab fa-behance-square", "l": "Behance square" },
			{ "c": "fas fa-bell", "l": "Bell" },
			{ "c": "fas fa-bell-slash", "l": "Bell slash" },
			{ "c": "fas fa-bicycle", "l": "Bicycle" },
			{ "c": "fas fa-binoculars", "l": "Binoculars" },
			{ "c": "fas fa-birthday-cake", "l": "Birthday cake" },
			{ "c": "fab fa-bitbucket", "l": "Bitbucket" },
			{ "c": "fab fa-black-tie", "l": "Black tie" },
			{ "c": "fas fa-bold", "l": "Bold" },
			{ "c": "fas fa-bolt", "l": "Bolt" },
			{ "c": "fas fa-bomb", "l": "Bomb" },
			{ "c": "fas fa-book", "l": "Book" },
			{ "c": "fas fa-bookmark", "l": "Bookmark" },
			{ "c": "fas fa-briefcase", "l": "Briefcase" },
			{ "c": "fab fa-btc", "l": "Btc" },
			{ "c": "fas fa-bug", "l": "Bug" },
			{ "c": "fas fa-building", "l": "Building" },
			{ "c": "fas fa-bullhorn", "l": "Bullhorn" },
			{ "c": "fas fa-bullseye", "l": "Bullseye" },
			{ "c": "fas fa-bus", "l": "Bus" },
			{ "c": "fab fa-buysellads", "l": "Buysellads" },
			{ "c": "fas fa-calculator", "l": "Calculator" },
			{ "c": "fas fa-calendar", "l": "Calendar" },
			{ "c": "fas fa-camera", "l": "Camera" },
			{ "c": "fas fa-camera-retro", "l": "Camera retro" },
			{ "c": "fas fa-car", "l": "Car" },
			{ "c": "fas fa-caret-down", "l": "Caret down" },
			{ "c": "fas fa-caret-left", "l": "Caret left" },
			{ "c": "fas fa-caret-right", "l": "Caret right" },
			{ "c": "fas fa-caret-up", "l": "Caret up" },
			{ "c": "fas fa-cart-arrow-down", "l": "Cart arrow down" },
			{ "c": "fas fa-cart-plus", "l": "Cart plus" },
			{ "c": "fab fa-cc-amex", "l": "Cc amex" },
			{ "c": "fas fa-certificate", "l": "Certificate" },
			{ "c": "fas fa-check", "l": "Check" },
			{ "c": "fas fa-check-circle", "l": "Check circle" },
			{ "c": "fas fa-check-square", "l": "Check square" },
			{ "c": "fas fa-chevron-circle-down", "l": "Chevron circle down" },
			{ "c": "fas fa-chevron-circle-left", "l": "Chevron circle left" },
			{ "c": "fas fa-chevron-circle-right", "l": "Chevron circle right" },
			{ "c": "fas fa-chevron-circle-up", "l": "Chevron circle up" },
			{ "c": "fas fa-chevron-down", "l": "Chevron down" },
			{ "c": "fas fa-chevron-left", "l": "Chevron left" },
			{ "c": "fas fa-chevron-right", "l": "Chevron right" },
			{ "c": "fas fa-chevron-up", "l": "Chevron up" },
			{ "c": "fas fa-child", "l": "Child" },
			{ "c": "fab fa-chrome", "l": "Chrome" },
			{ "c": "fas fa-circle", "l": "Circle" },
			{ "c": "fas fa-clipboard", "l": "Clipboard" },
			{ "c": "fas fa-clone", "l": "Clone" },
			{ "c": "fas fa-cloud", "l": "Cloud" },
			{ "c": "fas fa-code", "l": "Code" },
			{ "c": "fab fa-codepen", "l": "Codepen" },
			{ "c": "fas fa-coffee", "l": "Coffee" },
			{ "c": "fas fa-cog", "l": "Cog" },
			{ "c": "fas fa-cogs", "l": "Cogs" },
			{ "c": "fas fa-columns", "l": "Columns" },
			{ "c": "fas fa-comment", "l": "Comment" },
			{ "c": "fas fa-comments", "l": "Comments" },
			{ "c": "fas fa-compass", "l": "Compass" },
			{ "c": "fas fa-compress", "l": "Compress" },
			{ "c": "fas fa-copyright", "l": "Copyright" },
			{ "c": "fas fa-credit-card", "l": "Credit card" },
			{ "c": "fas fa-crop", "l": "Crop" },
			{ "c": "fas fa-crosshairs", "l": "Crosshairs" },
			{ "c": "fab fa-css3", "l": "Css3" },
			{ "c": "fas fa-cube", "l": "Cube" },
			{ "c": "fas fa-cubes", "l": "Cubes" },
			{ "c": "fab fa-dashcube", "l": "Dashcube" },
			{ "c": "fas fa-database", "l": "Database" },
			{ "c": "fab fa-delicious", "l": "Delicious" },
			{ "c": "fas fa-desktop", "l": "Desktop" },
			{ "c": "fab fa-deviantart", "l": "Deviantart" },
			{ "c": "fab fa-digg", "l": "Digg" },
			{ "c": "fas fa-download", "l": "Download" },
			{ "c": "fab fa-dribbble", "l": "Dribbble" },
			{ "c": "fab fa-dropbox", "l": "Dropbox" },
			{ "c": "fab fa-drupal", "l": "Drupal" },
			{ "c": "fas fa-eject", "l": "Eject" },
			{ "c": "fas fa-ellipsis-h", "l": "Ellipsis h" },
			{ "c": "fas fa-ellipsis-v", "l": "Ellipsis v" },
			{ "c": "fab fa-empire", "l": "Empire" },
			{ "c": "fas fa-envelope", "l": "Envelope" },
			{ "c": "fas fa-envelope-square", "l": "Envelope square" },
			{ "c": "fas fa-eraser", "l": "Eraser" },
			{ "c": "fas fa-exclamation", "l": "Exclamation" },
			{ "c": "fas fa-exclamation-circle", "l": "Exclamation circle" },
			{ "c": "fas fa-exclamation-triangle", "l": "Exclamation triangle" },
			{ "c": "fas fa-expand", "l": "Expand" },
			{ "c": "fab fa-expeditedssl", "l": "Expeditedssl" },
			{ "c": "fas fa-eye", "l": "Eye" },
			{ "c": "fas fa-eye-slash", "l": "Eye slash" },
			{ "c": "fab fa-facebook", "l": "Facebook" },
			{ "c": "fas fa-fast-backward", "l": "Fast backward" },
			{ "c": "fas fa-fast-forward", "l": "Fast forward" },
			{ "c": "fas fa-fax", "l": "Fax" },
			{ "c": "fas fa-female", "l": "Female" },
			{ "c": "fas fa-fighter-jet", "l": "Fighter jet" },
			{ "c": "fas fa-file", "l": "File" },
			{ "c": "fas fa-film", "l": "Film" },
			{ "c": "fas fa-filter", "l": "Filter" },
			{ "c": "fas fa-fire", "l": "Fire" },
			{ "c": "fas fa-fire-extinguisher", "l": "Fire extinguisher" },
			{ "c": "fab fa-firefox", "l": "Firefox" },
			{ "c": "fas fa-flag", "l": "Flag" },
			{ "c": "fas fa-flag-checkered", "l": "Flag checkered" },
			{ "c": "fas fa-flask", "l": "Flask" },
			{ "c": "fab fa-flickr", "l": "Flickr" },
			{ "c": "fas fa-folder", "l": "Folder" },
			{ "c": "fas fa-folder-open", "l": "Folder open" },
			{ "c": "fas fa-font", "l": "Font" },
			{ "c": "fab fa-fonticons", "l": "Fonticons" },
			{ "c": "fab fa-forumbee", "l": "Forumbee" },
			{ "c": "fas fa-forward", "l": "Forward" },
			{ "c": "fab fa-foursquare", "l": "Foursquare" },
			{ "c": "fas fa-gamepad", "l": "Gamepad" },
			{ "c": "fas fa-gavel", "l": "Gavel" },
			{ "c": "fas fa-genderless", "l": "Genderless" },
			{ "c": "fab fa-get-pocket", "l": "Get pocket" },
			{ "c": "fab fa-gg", "l": "Gg" },
			{ "c": "fab fa-gg-circle", "l": "Gg circle" },
			{ "c": "fas fa-gift", "l": "Gift" },
			{ "c": "fab fa-git", "l": "Git" },
			{ "c": "fab fa-git-square", "l": "Git square" },
			{ "c": "fab fa-github", "l": "Github" },
			{ "c": "fab fa-github-alt", "l": "Github alt" },
			{ "c": "fab fa-github-square", "l": "Github square" },
			{ "c": "fas fa-globe", "l": "Globe" },
			{ "c": "fab fa-google", "l": "Google" },
			{ "c": "fab fa-google-plus", "l": "Google plus" },
			{ "c": "fab fa-google-plus-square", "l": "Google plus square" },
			{ "c": "fab fa-google-wallet", "l": "Google wallet" },
			{ "c": "fas fa-graduation-cap", "l": "Graduation cap" },
			{ "c": "fab fa-gratipay", "l": "Gratipay" },
			{ "c": "fas fa-h-square", "l": "H square" },
			{ "c": "fab fa-hacker-news", "l": "Hacker news" },
			{ "c": "fas fa-headphones", "l": "Headphones" },
			{ "c": "fas fa-heart", "l": "Heart" },
			{ "c": "fas fa-heartbeat", "l": "Heartbeat" },
			{ "c": "fas fa-history", "l": "History" },
			{ "c": "fas fa-home", "l": "Home" },
			{ "c": "fas fa-hourglass", "l": "Hourglass" },
			{ "c": "fas fa-hourglass-end", "l": "Hourglass end" },
			{ "c": "fas fa-hourglass-half", "l": "Hourglass half" },
			{ "c": "fas fa-hourglass-start", "l": "Hourglass start" },
			{ "c": "fab fa-houzz", "l": "Houzz" },
			{ "c": "fab fa-html5", "l": "Html5" },
			{ "c": "fas fa-i-cursor", "l": "I cursor" },
			{ "c": "fas fa-inbox", "l": "Inbox" },
			{ "c": "fas fa-indent", "l": "Indent" },
			{ "c": "fas fa-industry", "l": "Industry" },
			{ "c": "fas fa-info", "l": "Info" },
			{ "c": "fas fa-info-circle", "l": "Info circle" },
			{ "c": "fab fa-instagram", "l": "Instagram" },
			{ "c": "fab fa-internet-explorer", "l": "Internet explorer" },
			{ "c": "fab fa-ioxhost", "l": "Ioxhost" },
			{ "c": "fas fa-italic", "l": "Italic" },
			{ "c": "fab fa-joomla", "l": "Joomla" },
			{ "c": "fab fa-jsfiddle", "l": "Jsfiddle" },
			{ "c": "fas fa-key", "l": "Key" },
			{ "c": "fas fa-language", "l": "Language" },
			{ "c": "fas fa-laptop", "l": "Laptop" },
			{ "c": "fab fa-lastfm", "l": "Lastfm" },
			{ "c": "fab fa-lastfm-square", "l": "Lastfm square" },
			{ "c": "fas fa-leaf", "l": "Leaf" },
			{ "c": "fab fa-leanpub", "l": "Leanpub" },
			{ "c": "fas fa-life-ring", "l": "Life ring" },
			{ "c": "fas fa-link", "l": "Link" },
			{ "c": "fab fa-linkedin", "l": "Linkedin" },
			{ "c": "fab fa-linux", "l": "Linux" },
			{ "c": "fas fa-list", "l": "List" },
			{ "c": "fas fa-list-alt", "l": "List alt" },
			{ "c": "fas fa-list-ol", "l": "List ol" },
			{ "c": "fas fa-list-ul", "l": "List ul" },
			{ "c": "fas fa-location-arrow", "l": "Location arrow" },
			{ "c": "fas fa-lock", "l": "Lock" },
			{ "c": "fas fa-magic", "l": "Magic" },
			{ "c": "fas fa-magnet", "l": "Magnet" },
			{ "c": "fas fa-male", "l": "Male" },
			{ "c": "fas fa-map", "l": "Map" },
			{ "c": "fas fa-map-marker", "l": "Map marker" },
			{ "c": "fas fa-map-pin", "l": "Map pin" },
			{ "c": "fas fa-map-signs", "l": "Map signs" },
			{ "c": "fas fa-mars", "l": "Mars" },
			{ "c": "fas fa-mars-double", "l": "Mars double" },
			{ "c": "fas fa-mars-stroke", "l": "Mars stroke" },
			{ "c": "fas fa-mars-stroke-h", "l": "Mars stroke h" },
			{ "c": "fas fa-mars-stroke-v", "l": "Mars stroke v" },
			{ "c": "fab fa-maxcdn", "l": "Maxcdn" },
			{ "c": "fab fa-medium", "l": "Medium" },
			{ "c": "fas fa-medkit", "l": "Medkit" },
			{ "c": "fas fa-mercury", "l": "Mercury" },
			{ "c": "fas fa-microphone", "l": "Microphone" },
			{ "c": "fas fa-microphone-slash", "l": "Microphone slash" },
			{ "c": "fas fa-minus", "l": "Minus" },
			{ "c": "fas fa-minus-circle", "l": "Minus circle" },
			{ "c": "fas fa-minus-square", "l": "Minus square" },
			{ "c": "fas fa-mobile", "l": "Mobile" },
			{ "c": "fas fa-motorcycle", "l": "Motorcycle" },
			{ "c": "fas fa-mouse-pointer", "l": "Mouse pointer" },
			{ "c": "fas fa-music", "l": "Music" },
			{ "c": "fas fa-neuter", "l": "Neuter" },
			{ "c": "fas fa-object-group", "l": "Object group" },
			{ "c": "fas fa-object-ungroup", "l": "Object ungroup" },
			{ "c": "fab fa-odnoklassniki", "l": "Odnoklassniki" },
			{ "c": "fab fa-odnoklassniki-square", "l": "Odnoklassniki square" },
			{ "c": "fab fa-opencart", "l": "Opencart" },
			{ "c": "fab fa-openid", "l": "Openid" },
			{ "c": "fab fa-opera", "l": "Opera" },
			{ "c": "fab fa-optin-monster", "l": "Optin monster" },
			{ "c": "fas fa-outdent", "l": "Outdent" },
			{ "c": "fab fa-pagelines", "l": "Pagelines" },
			{ "c": "fas fa-paint-brush", "l": "Paint brush" },
			{ "c": "fas fa-paper-plane", "l": "Paper plane" },
			{ "c": "fas fa-paperclip", "l": "Paperclip" },
			{ "c": "fas fa-paragraph", "l": "Paragraph" },
			{ "c": "fas fa-pause", "l": "Pause" },
			{ "c": "fas fa-paw", "l": "Paw" },
			{ "c": "fab fa-paypal", "l": "Paypal" },
			{ "c": "fas fa-phone", "l": "Phone" },
			{ "c": "fas fa-phone-square", "l": "Phone square" },
			{ "c": "fas fa-plane", "l": "Plane" },
			{ "c": "fas fa-play", "l": "Play" },
			{ "c": "fas fa-play-circle", "l": "Play circle" },
			{ "c": "fas fa-plug", "l": "Plug" },
			{ "c": "fas fa-plus", "l": "Plus" },
			{ "c": "fas fa-plus-circle", "l": "Plus circle" },
			{ "c": "fas fa-plus-square", "l": "Plus square" },
			{ "c": "fas fa-power-off", "l": "Power off" },
			{ "c": "fas fa-print", "l": "Print" },
			{ "c": "fas fa-puzzle-piece", "l": "Puzzle piece" },
			{ "c": "fab fa-qq", "l": "Qq" },
			{ "c": "fas fa-qrcode", "l": "Qrcode" },
			{ "c": "fas fa-question", "l": "Question" },
			{ "c": "fas fa-question-circle", "l": "Question circle" },
			{ "c": "fas fa-quote-left", "l": "Quote left" },
			{ "c": "fas fa-quote-right", "l": "Quote right" },
			{ "c": "fas fa-random", "l": "Random" },
			{ "c": "fab fa-rebel", "l": "Rebel" },
			{ "c": "fas fa-recycle", "l": "Recycle" },
			{ "c": "fab fa-reddit", "l": "Reddit" },
			{ "c": "fab fa-reddit-square", "l": "Reddit square" },
			{ "c": "fas fa-sync", "l": "Refresh" },
			{ "c": "fas fa-registered", "l": "Registered" },
			{ "c": "fab fa-renren", "l": "Renren" },
			{ "c": "fas fa-reply", "l": "Reply" },
			{ "c": "fas fa-reply-all", "l": "Reply all" },
			{ "c": "fas fa-retweet", "l": "Retweet" },
			{ "c": "fas fa-road", "l": "Road" },
			{ "c": "fas fa-rocket", "l": "Rocket" },
			{ "c": "fas fa-rss", "l": "Rss" },
			{ "c": "fas fa-rss-square", "l": "Rss square" },
			{ "c": "fas fa-search", "l": "Search" },
			{ "c": "fas fa-search-minus", "l": "Search minus" },
			{ "c": "fas fa-search-plus", "l": "Search plus" },
			{ "c": "fab fa-sellsy", "l": "Sellsy" },
			{ "c": "fas fa-server", "l": "Server" },
			{ "c": "fas fa-share", "l": "Share" },
			{ "c": "fas fa-share-alt", "l": "Share alt" },
			{ "c": "fas fa-share-alt-square", "l": "Share alt square" },
			{ "c": "fas fa-share-square", "l": "Share square" },
			{ "c": "fas fa-ship", "l": "Ship" },
			{ "c": "fab fa-shirtsinbulk", "l": "Shirtsinbulk" },
			{ "c": "fas fa-shopping-cart", "l": "Shopping cart" },
			{ "c": "fas fa-signal", "l": "Signal" },
			{ "c": "fab fa-simplybuilt", "l": "Simplybuilt" },
			{ "c": "fas fa-sitemap", "l": "Sitemap" },
			{ "c": "fab fa-skyatlas", "l": "Skyatlas" },
			{ "c": "fab fa-skype", "l": "Skype" },
			{ "c": "fab fa-slack", "l": "Slack" },
			{ "c": "fab fa-slideshare", "l": "Slideshare" },
			{ "c": "fas fa-sort", "l": "Sort" },
			{ "c": "fab fa-soundcloud", "l": "Soundcloud" },
			{ "c": "fas fa-space-shuttle", "l": "Space shuttle" },
			{ "c": "fas fa-spinner", "l": "Spinner" },
			{ "c": "fab fa-spotify", "l": "Spotify" },
			{ "c": "fas fa-square", "l": "Square" },
			{ "c": "fab fa-stack-exchange", "l": "Stack exchange" },
			{ "c": "fab fa-stack-overflow", "l": "Stack overflow" },
			{ "c": "fas fa-star", "l": "Star" },
			{ "c": "fas fa-star-half", "l": "Star half" },
			{ "c": "fab fa-steam", "l": "Steam" },
			{ "c": "fab fa-steam-square", "l": "Steam square" },
			{ "c": "fas fa-step-backward", "l": "Step backward" },
			{ "c": "fas fa-step-forward", "l": "Step forward" },
			{ "c": "fas fa-stethoscope", "l": "Stethoscope" },
			{ "c": "fas fa-sticky-note", "l": "Sticky note" },
			{ "c": "fas fa-stop", "l": "Stop" },
			{ "c": "fas fa-street-view", "l": "Street view" },
			{ "c": "fas fa-strikethrough", "l": "Strikethrough" },
			{ "c": "fab fa-stumbleupon", "l": "Stumbleupon" },
			{ "c": "fab fa-stumbleupon-circle", "l": "Stumbleupon circle" },
			{ "c": "fas fa-subscript", "l": "Subscript" },
			{ "c": "fas fa-subway", "l": "Subway" },
			{ "c": "fas fa-suitcase", "l": "Suitcase" },
			{ "c": "fas fa-superscript", "l": "Superscript" },
			{ "c": "fas fa-table", "l": "Table" },
			{ "c": "fas fa-tablet", "l": "Tablet" },
			{ "c": "fas fa-tag", "l": "Tag" },
			{ "c": "fas fa-tags", "l": "Tags" },
			{ "c": "fas fa-tasks", "l": "Tasks" },
			{ "c": "fas fa-taxi", "l": "Taxi" },
			{ "c": "fab fa-tencent-weibo", "l": "Tencent weibo" },
			{ "c": "fas fa-terminal", "l": "Terminal" },
			{ "c": "fas fa-text-height", "l": "Text height" },
			{ "c": "fas fa-text-width", "l": "Text width" },
			{ "c": "fas fa-th", "l": "Th" },
			{ "c": "fas fa-th-large", "l": "Th large" },
			{ "c": "fas fa-th-list", "l": "Th list" },
			{ "c": "fas fa-thumbs-down", "l": "Thumbs down" },
			{ "c": "fas fa-thumbs-up", "l": "Thumbs up" },
			{ "c": "fas fa-times", "l": "Times" },
			{ "c": "fas fa-times-circle", "l": "Times circle" },
			{ "c": "fas fa-tint", "l": "Tint" },
			{ "c": "fas fa-toggle-off", "l": "Toggle off" },
			{ "c": "fas fa-toggle-on", "l": "Toggle on" },
			{ "c": "fas fa-trademark", "l": "Trademark" },
			{ "c": "fas fa-train", "l": "Train" },
			{ "c": "fas fa-transgender", "l": "Transgender" },
			{ "c": "fas fa-transgender-alt", "l": "Transgender alt" },
			{ "c": "fas fa-trash", "l": "Trash" },
			{ "c": "fas fa-tree", "l": "Tree" },
			{ "c": "fab fa-trello", "l": "Trello" },
			{ "c": "fab fa-tripadvisor", "l": "Tripadvisor" },
			{ "c": "fas fa-trophy", "l": "Trophy" },
			{ "c": "fas fa-truck", "l": "Truck" },
			{ "c": "fas fa-tty", "l": "Tty" },
			{ "c": "fab fa-tumblr", "l": "Tumblr" },
			{ "c": "fab fa-tumblr-square", "l": "Tumblr square" },
			{ "c": "fab fa-twitch", "l": "Twitch" },
			{ "c": "fab fa-twitter", "l": "Twitter" },
			{ "c": "fab fa-twitter-square", "l": "Twitter square" },
			{ "c": "fas fa-umbrella", "l": "Umbrella" },
			{ "c": "fas fa-underline", "l": "Underline" },
			{ "c": "fas fa-undo", "l": "Undo" },
			{ "c": "fas fa-university", "l": "University" },
			{ "c": "fas fa-unlock", "l": "Unlock" },
			{ "c": "fas fa-unlock-alt", "l": "Unlock alt" },
			{ "c": "fas fa-upload", "l": "Upload" },
			{ "c": "fas fa-user", "l": "User" },
			{ "c": "fas fa-user-md", "l": "User md" },
			{ "c": "fas fa-user-plus", "l": "User plus" },
			{ "c": "fas fa-user-secret", "l": "User secret" },
			{ "c": "fas fa-user-times", "l": "User times" },
			{ "c": "fas fa-users", "l": "Users" },
			{ "c": "fas fa-venus", "l": "Venus" },
			{ "c": "fas fa-venus-double", "l": "Venus double" },
			{ "c": "fas fa-venus-mars", "l": "Venus mars" },
			{ "c": "fas fa-vimeo", "l": "Vimeo" },
			{ "c": "fas fa-volume-down", "l": "Volume down" },
			{ "c": "fas fa-volume-off", "l": "Volume off" },
			{ "c": "fas fa-volume-up", "l": "Volume up" },
			{ "c": "fas fa-wheelchair", "l": "Wheelchair" },
			{ "c": "fas fa-wifi", "l": "Wifi" },
			{ "c": "fas fa-wrench", "l": "Wrench" },
			{ "c": "fas fa-youtube-square", "l": "Youtube square" }
		],
		"dashboardView": [
			{
				"id": 1,
				"name": "Zone View"
			}
			, {
				"id": 2,
				"name": "Stats Dashboard"
			}
			, {
				"id": 3,
				"name": "Floor Layout"
			}
			, {
				"id": 4,
				"name": "Monitor Entry & Exit "
			}
			, {
				"id": 5,
				"name": "Asset Tracking"
			}
			, {
				"id": 6,
				"name": "Heat Map"
			}
			, {
				"id": 7,
				"name": "Map View"
			}
		]

	});




